"""Initial migration - create all tables

Revision ID: 7b54b93bb28c
Revises: 
Create Date: 2026-02-11 12:08:43.953766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b54b93bb28c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_schema_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_schema_cache_id'), 'api_schema_cache', ['id'], unique=False)
    op.create_table('api_testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_testcases_id'), 'api_testcases', ['id'], unique=False)
    op.create_table('locator_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('primary_locator', sa.String(), nullable=False),
    sa.Column('healed_locators', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locator_registry_id'), 'locator_registry', ['id'], unique=False)
    op.create_table('schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemas_id'), 'schemas', ['id'], unique=False)
    op.create_table('ui_testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_testcases_id'), 'ui_testcases', ['id'], unique=False)
    op.create_table('api_execution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['api_testcases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_execution_runs_id'), 'api_execution_runs', ['id'], unique=False)
    op.create_table('synthetic_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_runs_id'), 'synthetic_runs', ['id'], unique=False)
    op.create_table('ui_execution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('logs_path', sa.String(), nullable=True),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['ui_testcases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_execution_runs_id'), 'ui_execution_runs', ['id'], unique=False)
    op.create_table('synthetic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('row_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['synthetic_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_data_id'), 'synthetic_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synthetic_data_id'), table_name='synthetic_data')
    op.drop_table('synthetic_data')
    op.drop_index(op.f('ix_ui_execution_runs_id'), table_name='ui_execution_runs')
    op.drop_table('ui_execution_runs')
    op.drop_index(op.f('ix_synthetic_runs_id'), table_name='synthetic_runs')
    op.drop_table('synthetic_runs')
    op.drop_index(op.f('ix_api_execution_runs_id'), table_name='api_execution_runs')
    op.drop_table('api_execution_runs')
    op.drop_index(op.f('ix_ui_testcases_id'), table_name='ui_testcases')
    op.drop_table('ui_testcases')
    op.drop_index(op.f('ix_schemas_id'), table_name='schemas')
    op.drop_table('schemas')
    op.drop_index(op.f('ix_locator_registry_id'), table_name='locator_registry')
    op.drop_table('locator_registry')
    op.drop_index(op.f('ix_api_testcases_id'), table_name='api_testcases')
    op.drop_table('api_testcases')
    op.drop_index(op.f('ix_api_schema_cache_id'), table_name='api_schema_cache')
    op.drop_table('api_schema_cache')
    # ### end Alembic commands ###
