"""Add script column to ui_testcases

Revision ID: e24d2916597b
Revises: 7b54b93bb28c
Create Date: 2026-02-11 12:31:00.045335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24d2916597b'
down_revision = '7b54b93bb28c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ui_testcases', sa.Column('script', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ui_testcases', 'script')
    # ### end Alembic commands ###
